###  정렬 방식 (최신순)
GET localhost:8080/api/study-channels?page=1&size=6&sort=RECENT

### 정렬 방식 (인기순)
GET localhost:8080/api/study-channels?page=1&size=6&sort=POPULAR

### 페이징 번호와 크기
GET localhost:8080/api/study-channels?page=2&size=3

###  필터 조건 (모집중)
GET localhost:8080/api/study-channels?status=RECRUITING

### 필터 조건 (오프라인)
GET localhost:8080/api/study-channels?type=OFFLINE

### 필터 조건 (모집중 & 오프라인)
GET localhost:8080/api/study-channels?status=RECRUITING&type=OFFLINE

### 필터 조건 (카테고리)
GET localhost:8080/api/study-channels?category=IT

### 필터 조건 (모집 상태 & 오프라인 & 카테고리)
GET localhost:8080/api/study-channels?page=5&status=RECRUITING&type=OFFLINE&category=IT

### 필터 조건 (모집 상태 & 카테고리)
GET localhost:8080/api/study-channels?status=RECRUITING&category=IT

### 필터 조건 (오프라인 & 카테고리)
GET localhost:8080/api/study-channels?type=OFFLINE&category=IT

### 특정 스터디 채널 조회
GET localhost:8080/api/study-channels/1
